### ISSUE TITLE
[Bug]: Intercepting breaks docker-compose inter-service requests

### ISSUE THREAD

**Issue by Caerbannog** [httptoolkit/httptoolkit#333]
### Repro steps

1. Click "Fresh Terminal" or "Existing Terminal"
2. Create a docker-compose file with two services that communicate with each other through their service name (see below)
3. Start the docker-compose
4. The inter-service request is intercepted
5. The inter-service request fails to resolve the service hostname: `Error: getaddrinfo ENOTFOUND api`

Simplified docker-compose file:
```yml
version: '2.2'

services:
  api:
    build: ./api

  tester:
    build: ./tester
    depends_on:
      - api
```

Simplified `./tester/Dockerfile`:
```dockerfile
FROM alpine:3.14.3
CMD ./tester.sh
```

Simplified `./tester/tester.sh` script:
```sh
curl --fail api:8080
```

### How often does this bug happen?

Often

### The desktop OS you're using

Ubuntu 22.04

### Error screenshot

![image](https://user-images.githubusercontent.com/242172/191938075-2a122f26-8445-41c7-8662-b265a011f74d.png)
